import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
const url=process.env.REVIEW_URL||'http://127.0.0.1:8015/';
const catalog=JSON.parse(await readFile('data/rounds.json','utf8'));
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1100},acceptDownloads:true});
const errors=[],posts=[];
page.on('pageerror',error=>errors.push(error.message));
try{
 await page.route('**/upload-config.json',route=>route.fulfill({json:{endpoint:'https://round-test.example',round_ids:catalog.rounds.map(r=>r.round_id)}}));
 await page.route('https://round-test.example/**',route=>{
  const headers={'access-control-allow-origin':'*','access-control-allow-methods':'GET, POST, OPTIONS','access-control-allow-headers':'Content-Type, X-Upload-Key'};
  if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers});
  const body=route.request().postDataJSON();posts.push(body);
  return route.fulfill({headers,json:{state:'draft',count:body.records.length}});
 });
 await page.goto(url);
 await page.waitForFunction(()=>document.querySelector('#progress').textContent.includes('/ 250'));
 assert.equal(await page.locator('#round option').count(),4);
 const choices=['a','b','neither','both'];
 const storageKeys=[];
 for(let i=0;i<4;i++){
  const entry=catalog.rounds[i];
  if(i)await page.locator('#round').selectOption(entry.id);
  await page.waitForFunction(id=>document.querySelector('#round').value===id && document.querySelector('#progress').textContent.includes('0 / 250'),entry.id);
  await page.waitForFunction(()=>[...document.querySelectorAll('.image-box img')].every(im=>im.complete&&im.naturalWidth>0));
  assert.match(await page.locator('#round-destination').textContent(),new RegExp(entry.id));
  await page.locator('[data-choice="'+choices[i]+'"]').click();
  if(choices[i]==='neither')await page.locator('[value="color"]').check();
  if(choices[i]==='both')await page.locator('#preferred').selectOption('b');
  await page.locator('#caption').fill('a pet reviewed in '+entry.id);
  await page.locator('#save').click();
  await page.waitForFunction(()=>document.querySelector('#progress').textContent.includes('1 / 250'));
  await page.waitForFunction(()=>document.querySelector('#upload-state').textContent.includes('满 25 张后自动提交'));
  assert.equal(posts.at(-1).round_id,entry.round_id);
  assert.ok(posts.at(-1).records.every(row=>row.round_id===entry.round_id&&row.photo_id==='000'));
  storageKeys.push(await page.evaluate(rid=>Object.keys(localStorage).find(k=>k.startsWith('cartoon-review:')&&k.endsWith(rid)),entry.round_id));
 }
 assert.equal(new Set(storageKeys).size,4);
 await page.locator('#round').selectOption('round_2');
 await page.waitForFunction(()=>document.querySelector('#round').value==='round_2'&&document.querySelector('#progress').textContent.includes('1 / 250'));
 await page.locator('#filter').selectOption('all');
 assert.equal(await page.locator('#caption').inputValue(),'a pet reviewed in round_2');
 assert.equal(await page.locator('[data-choice="b"]').getAttribute('aria-pressed'),'true');
 const download=page.waitForEvent('download');await page.locator('#export-now').click();
 const row=JSON.parse(await readFile(await (await download).path(),'utf8'));
 await page.locator('#round').selectOption('round_3');
 await page.waitForFunction(()=>document.querySelector('#round').value==='round_3'&&document.querySelector('#progress').textContent.includes('1 / 250'));
 await page.locator('#import').setInputFiles({name:'cross-round.jsonl',mimeType:'application/x-ndjson',buffer:Buffer.from(JSON.stringify(row))});
 await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('导入失败'));
 await page.locator('#range').fill('225-249');await page.locator('#apply-range').click();
 assert.equal(await page.locator('#next-group').isDisabled(),true);
 await page.locator('#range').fill('250-274');await page.locator('#apply-range').click();
 assert.match(await page.locator('#message').textContent(),/0–249/);
 await page.locator('#range').fill('0-24');await page.locator('#apply-range').click();
 await page.locator('#filter').selectOption('all');
 await mkdir('.test-output',{recursive:true});
 await page.screenshot({path:'.test-output/four-rounds-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:'.test-output/four-rounds-mobile.png',fullPage:true});
 await page.goto(new URL('?round=round_1&archive=1&range=450-474',url).href);
 await page.waitForFunction(()=>document.querySelector('#progress').textContent.includes('/ 500'));
 assert.match(await page.locator('#item-title').textContent(),/^450/);
 await page.goto(url);
 await page.waitForFunction(()=>document.querySelector('#progress').textContent.includes('1 / 250'));
 assert.deepEqual(errors,[]);
 console.log('Four-round browser passed: isolated save/reload, per-round upload identity, cross-round import rejection, bounds, legacy archive, and mobile layout.');
}finally{await browser.close();}
